basePath: '{{.BasePath}}'
definitions:
  model.ContractRequest:
    properties:
      electronic_contract:
        type: string
      paper_contract:
        type: string
    type: object
  model.Message:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: integer
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: YANFEI-CONTRACT API
  version: 0.0.1
paths:
  /contract/new:
    post:
      consumes:
      - application/json
      description: 上传新的合同
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 电子合同信息
        in: body
        name: contract
        required: true
        schema:
          $ref: '#/definitions/model.ContractRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
            type: object
      summary: 上传新的合同
      tags:
      - 合同相关
  /oss/signture:
    get:
      consumes:
      - application/json
      description: 生成oss上传签名
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
            type: object
      summary: 生成oss上传签名
      tags:
      - OSS
swagger: "2.0"
